services:
    laravel-nginx:
        container_name: "laravel-nginx"
        build:
            context: ./docker/nginx
        depends_on:
            - laravel-app
        ports:
            - 80:80
        volumes:
            - ./:/src

    laravel-app:
        container_name: "laravel-app"
        build:
            context: ./docker/php
        depends_on:
            - laravel-mysql
        ports:
            - 5173:5173
        volumes:
            - ./:/src
            - /src/node_modules
            - /src/vendor
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    # .envファイルの「DB_HOST」とサービス名を合わせる
    laravel-mysql:
        image: mysql:8.0
        # image: mysql:latest
        container_name: laravel-mysql
        environment:
            # MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_PASSWORD: root
            # .envファイルの「DB_DATABASE」とMYSQL_DATABASEを合わせる
            MYSQL_DATABASE: laraveltest
            TZ: "Asia/Tokyo"
        # 文字コード指定
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=32505856
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin-newlaravel:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-laravel
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=laravel-mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - UPLOAD_LIMIT=300M
        links:
            - laravel-mysql
        ports:
            - 8580:80
        volumes:
            - /sessions

    laravel-redis:
        image: redis:alpine
        container_name: "laravel-redis"
        ports:
            - 16379:6379
